# Day 6 – SQL Business Queries

## Objective

Execute SQL business queries using SQLite and Python.

### Skills Demonstrated

- SQLite
- SQL
- Python
- Pandas
- Business Analytics

In [30]:
import sqlite3
import pandas as pd

In [31]:
conn = sqlite3.connect("hr_database.db")

print("Database Connected Successfully!")

Database Connected Successfully!

In [32]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

        name
0  employees

In [33]:
query = """
SELECT *
FROM employees
LIMIT 5;
"""

pd.read_sql(query, conn)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [34]:
query = """
SELECT
    COUNT(*) AS TotalEmployees
FROM employees;
"""

pd.read_sql(query, conn)

   TotalEmployees
0            1470

In [35]:
query = """
SELECT
    Attrition,
    COUNT(*) AS Employees
FROM employees
GROUP BY Attrition;
"""

pd.read_sql(query, conn)

  Attrition  Employees
0        No       1233
1       Yes        237

In [36]:
query = """
SELECT
    ROUND(AVG(MonthlyIncome),2) AS AverageSalary
FROM employees;
"""

pd.read_sql(query, conn)

   AverageSalary
0        6502.93

## Query 4 – Average Salary by Department

### Objective

Identify which departments pay the highest average monthly salary.

In [37]:
query = """
SELECT
    Department,
    ROUND(AVG(MonthlyIncome),2) AS AverageSalary
FROM employees
GROUP BY Department
ORDER BY AverageSalary DESC;
"""

pd.read_sql(query, conn)

               Department  AverageSalary
0                   Sales        6959.17
1         Human Resources        6654.51
2  Research & Development        6281.25

## Query 5 – Attrition by Department

### Objective

Count employee attrition across departments.

In [38]:
query = """
SELECT
    Department,
    Attrition,
    COUNT(*) AS Employees
FROM employees
GROUP BY Department, Attrition
ORDER BY Department;
"""

pd.read_sql(query, conn)

               Department Attrition  Employees
0         Human Resources        No         51
1         Human Resources       Yes         12
2  Research & Development        No        828
3  Research & Development       Yes        133
4                   Sales        No        354
5                   Sales       Yes         92

## Query 6 – Average Age by Department

### Objective

Find the average employee age in each department.

In [39]:
query = """
SELECT
    Department,
    ROUND(AVG(Age),1) AS AverageAge
FROM employees
GROUP BY Department
ORDER BY AverageAge DESC;
"""

pd.read_sql(query, conn)

               Department  AverageAge
0         Human Resources        37.8
1  Research & Development        37.0
2                   Sales        36.5

## Query 7 – Average Working Experience

### Objective

Compare average total working years across job roles.

In [40]:
query = """
SELECT
    JobRole,
    ROUND(AVG(TotalWorkingYears),2) AS AvgExperience
FROM employees
GROUP BY JobRole
ORDER BY AvgExperience DESC;
"""

pd.read_sql(query, conn)

                     JobRole  AvgExperience
0                    Manager          24.55
1          Research Director          21.40
2  Healthcare Representative          14.07
3     Manufacturing Director          12.79
4            Sales Executive          11.10
5            Human Resources           8.17
6         Research Scientist           7.72
7      Laboratory Technician           7.66
8       Sales Representative           4.67

## Query 8 – Overtime Distribution

### Objective

Determine how many employees work overtime.

In [41]:
query = """
SELECT
    OverTime,
    COUNT(*) AS Employees
FROM employees
GROUP BY OverTime;
"""

pd.read_sql(query, conn)

  OverTime  Employees
0       No       1054
1      Yes        416

## Query 9 – Employees by Job Role

### Objective

Identify the largest job roles in the organization.

In [42]:
query = """
SELECT
    JobRole,
    COUNT(*) AS Employees
FROM employees
GROUP BY JobRole
ORDER BY Employees DESC;
"""

pd.read_sql(query, conn)

                     JobRole  Employees
0            Sales Executive        326
1         Research Scientist        292
2      Laboratory Technician        259
3     Manufacturing Director        145
4  Healthcare Representative        131
5                    Manager        102
6       Sales Representative         83
7          Research Director         80
8            Human Resources         52

## Query 10 – Highest Paying Job Roles

### Objective

Compare average monthly income across job roles.

In [43]:
query = """
SELECT
    JobRole,
    ROUND(AVG(MonthlyIncome),2) AS AverageSalary
FROM employees
GROUP BY JobRole
ORDER BY AverageSalary DESC;
"""

pd.read_sql(query, conn)

                     JobRole  AverageSalary
0                    Manager       17181.68
1          Research Director       16033.55
2  Healthcare Representative        7528.76
3     Manufacturing Director        7295.14
4            Sales Executive        6924.28
5            Human Resources        4235.75
6         Research Scientist        3239.97
7      Laboratory Technician        3237.17
8       Sales Representative        2626.00

query = """
SELECT
    JobRole,
    ROUND(AVG(MonthlyIncome),2) AS AverageSalary
FROM employees
GROUP BY JobRole
ORDER BY AverageSalary DESC;
"""

pd.read_sql(query, conn)

In [44]:
query = """
SELECT
    Department,
    ROUND(
        SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/
        COUNT(*),2
    ) AS AttritionRate
FROM employees
GROUP BY Department
ORDER BY AttritionRate DESC;
"""

pd.read_sql(query, conn)

               Department  AttritionRate
0                   Sales          20.63
1         Human Resources          19.05
2  Research & Development          13.84

## Query 12 – Attrition Rate by Job Role

### Objective

Identify job roles with the highest attrition.

In [45]:
query = """
SELECT
    JobRole,
    ROUND(
        SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/
        COUNT(*),2
    ) AS AttritionRate
FROM employees
GROUP BY JobRole
ORDER BY AttritionRate DESC;
"""

pd.read_sql(query, conn)

                     JobRole  AttritionRate
0       Sales Representative          39.76
1      Laboratory Technician          23.94
2            Human Resources          23.08
3            Sales Executive          17.48
4         Research Scientist          16.10
5     Manufacturing Director           6.90
6  Healthcare Representative           6.87
7                    Manager           4.90
8          Research Director           2.50

## Query 13 – Average Salary by Job Level

### Objective

Analyze salary growth across job levels.

In [46]:
query = """
SELECT
    JobLevel,
    ROUND(AVG(MonthlyIncome),2) AS AverageSalary
FROM employees
GROUP BY JobLevel
ORDER BY JobLevel;
"""

pd.read_sql(query, conn)

   JobLevel  AverageSalary
0         1        2786.92
1         2        5502.28
2         3        9817.25
3         4       15503.78
4         5       19191.83

## Query 14 – Business Travel Distribution

### Objective

Find how many employees fall into each travel category.

In [47]:
query = """
SELECT
    BusinessTravel,
    COUNT(*) AS Employees
FROM employees
GROUP BY BusinessTravel
ORDER BY Employees DESC;
"""

pd.read_sql(query, conn)

      BusinessTravel  Employees
0      Travel_Rarely       1043
1  Travel_Frequently        277
2         Non-Travel        150

## Query 15 – Salary by Education Field

### Objective

Compare average salaries across education backgrounds.

In [48]:
query = """
SELECT
    EducationField,
    ROUND(AVG(MonthlyIncome),2) AS AverageSalary
FROM employees
GROUP BY EducationField
ORDER BY AverageSalary DESC;
"""

pd.read_sql(query, conn)

     EducationField  AverageSalary
0         Marketing        7348.58
1   Human Resources        7241.15
2           Medical        6510.04
3     Life Sciences        6463.29
4             Other        6071.55
5  Technical Degree        5758.30

## Query 16 – Average Distance from Home

### Objective

Measure the average commuting distance by department.

In [49]:
query = """
SELECT
    Department,
    ROUND(AVG(DistanceFromHome),2) AS AvgDistance
FROM employees
GROUP BY Department
ORDER BY AvgDistance DESC;
"""

pd.read_sql(query, conn)

               Department  AvgDistance
0                   Sales         9.37
1  Research & Development         9.14
2         Human Resources         8.70

## Query 17 – Job Satisfaction

### Objective

Calculate average job satisfaction by department.

In [50]:
query = """
SELECT
    Department,
    ROUND(AVG(JobSatisfaction),2) AS AvgJobSatisfaction
FROM employees
GROUP BY Department
ORDER BY AvgJobSatisfaction DESC;
"""

pd.read_sql(query, conn)

               Department  AvgJobSatisfaction
0                   Sales                2.75
1  Research & Development                2.73
2         Human Resources                2.60

## Query 18 – Work-Life Balance

### Objective

Compare average work-life balance across departments.

In [51]:
query = """
SELECT
    Department,
    ROUND(AVG(WorkLifeBalance),2) AS AvgWorkLifeBalance
FROM employees
GROUP BY Department
ORDER BY AvgWorkLifeBalance DESC;
"""

pd.read_sql(query, conn)

               Department  AvgWorkLifeBalance
0         Human Resources                2.92
1                   Sales                2.82
2  Research & Development                2.73

## Query 19 – Employee Tenure

### Objective

Determine the average tenure in each department.

In [52]:
query = """
SELECT
    Department,
    ROUND(AVG(YearsAtCompany),2) AS AvgYears
FROM employees
GROUP BY Department
ORDER BY AvgYears DESC;
"""

pd.read_sql(query, conn)

               Department  AvgYears
0                   Sales      7.28
1         Human Resources      7.24
2  Research & Development      6.86

## Query 20 – Department Salary Ranking

### Objective

Rank departments based on average monthly income.

In [53]:
query = """
SELECT
    Department,
    ROUND(AVG(MonthlyIncome),2) AS AvgSalary
FROM employees
GROUP BY Department
ORDER BY AvgSalary DESC;
"""

pd.read_sql(query, conn)

               Department  AvgSalary
0                   Sales    6959.17
1         Human Resources    6654.51
2  Research & Development    6281.25

## Query 21 – Large Departments

### Objective

Find departments having more than 300 employees.

In [54]:
query = """
SELECT
    Department,
    COUNT(*) AS Employees
FROM employees
GROUP BY Department
HAVING COUNT(*) > 300;
"""

pd.read_sql(query, conn)

               Department  Employees
0  Research & Development        961
1                   Sales        446

## Query 22 – Employees Above Average Salary

### Objective

Find employees earning above the company average salary.

In [55]:
query = """
SELECT
    EmployeeNumber,
    Department,
    MonthlyIncome
FROM employees
WHERE MonthlyIncome >
(
    SELECT AVG(MonthlyIncome)
    FROM employees
)
ORDER BY MonthlyIncome DESC;
"""

pd.read_sql(query, conn)

     EmployeeNumber              Department  MonthlyIncome
0               259  Research & Development          19999
1              1035  Research & Development          19973
2              1191  Research & Development          19943
3               226  Research & Development          19926
4               787  Research & Development          19859
..              ...                     ...            ...
488             496  Research & Development           6540
489             523                   Sales           6538
490             889                   Sales           6524
491            1724  Research & Development           6516
492            1822  Research & Development           6513

[493 rows x 3 columns]

## Query 23 – Highest Salary by Department

### Objective

Identify the highest paid employee in every department.

In [56]:
query = """
SELECT
    Department,
    MAX(MonthlyIncome) AS HighestSalary
FROM employees
GROUP BY Department;
"""

pd.read_sql(query, conn)

               Department  HighestSalary
0         Human Resources          19717
1  Research & Development          19999
2                   Sales          19847

## Query 24 – Department Salary Ranking

### Objective

Rank departments by average salary.

In [57]:
query = """
SELECT
    Department,
    ROUND(AVG(MonthlyIncome),2) AS AvgSalary
FROM employees
GROUP BY Department
ORDER BY AvgSalary DESC;
"""

pd.read_sql(query, conn)

               Department  AvgSalary
0                   Sales    6959.17
1         Human Resources    6654.51
2  Research & Development    6281.25

## Query 25 – Salary Ranking

### Objective

Rank employees based on monthly income.

In [58]:
query = """
SELECT
    EmployeeNumber,
    MonthlyIncome,
    RANK() OVER(
        ORDER BY MonthlyIncome DESC
    ) AS SalaryRank
FROM employees;
"""

pd.read_sql(query, conn)

      EmployeeNumber  MonthlyIncome  SalaryRank
0                259          19999           1
1               1035          19973           2
2               1191          19943           3
3                226          19926           4
4                787          19859           5
...              ...            ...         ...
1465            1928           1091        1466
1466            1876           1081        1467
1467            1056           1052        1468
1468            1012           1051        1469
1469             701           1009        1470

[1470 rows x 3 columns]

## Query 26 – Top Paid Employees

### Objective

Display the highest paid employees.

In [59]:
query = """
SELECT
    EmployeeNumber,
    Department,
    MonthlyIncome
FROM employees
ORDER BY MonthlyIncome DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

   EmployeeNumber              Department  MonthlyIncome
0             259  Research & Development          19999
1            1035  Research & Development          19973
2            1191  Research & Development          19943
3             226  Research & Development          19926
4             787  Research & Development          19859
5            1282                   Sales          19847
6            1038                   Sales          19845
7            1740                   Sales          19833
8            1255  Research & Development          19740
9            1338         Human Resources          19717

## Query 27 – Salary Rank Within Department

### Objective

Rank employees by salary inside each department.

In [60]:
query = """
SELECT
    EmployeeNumber,
    Department,
    MonthlyIncome,
    RANK() OVER(
        PARTITION BY Department
        ORDER BY MonthlyIncome DESC
    ) AS DepartmentRank
FROM employees;
"""

pd.read_sql(query, conn)

      EmployeeNumber       Department  MonthlyIncome  DepartmentRank
0               1338  Human Resources          19717               1
1               1625  Human Resources          19658               2
2               1973  Human Resources          19636               3
3                734  Human Resources          19189               4
4                731  Human Resources          19141               5
...              ...              ...            ...             ...
1465             411            Sales           1200             442
1466            1273            Sales           1118             443
1467            1928            Sales           1091             444
1468            1876            Sales           1081             445
1469            1056            Sales           1052             446

[1470 rows x 4 columns]

## Query 28 – Running Average Salary

### Objective

Calculate cumulative average salary.

In [61]:
query = """
SELECT
    EmployeeNumber,
    MonthlyIncome,
    AVG(MonthlyIncome) OVER(
        ORDER BY MonthlyIncome
    ) AS RunningAverage
FROM employees;
"""

pd.read_sql(query, conn)

      EmployeeNumber  MonthlyIncome  RunningAverage
0                701           1009     1009.000000
1               1012           1051     1030.000000
2               1056           1052     1037.333333
3               1876           1081     1048.250000
4               1928           1091     1056.800000
...              ...            ...             ...
1465             787          19859     6466.212824
1466             226          19926     6475.387866
1467            1191          19943     6484.561989
1468            1035          19973     6493.744044
1469             259          19999     6502.931293

[1470 rows x 3 columns]

## Query 29 – Dense Salary Ranking

### Objective

Assign dense ranks based on salary.

In [62]:
query = """
SELECT
    EmployeeNumber,
    MonthlyIncome,
    DENSE_RANK() OVER(
        ORDER BY MonthlyIncome DESC
    ) AS DenseSalaryRank
FROM employees;
"""

pd.read_sql(query, conn)

      EmployeeNumber  MonthlyIncome  DenseSalaryRank
0                259          19999                1
1               1035          19973                2
2               1191          19943                3
3                226          19926                4
4                787          19859                5
...              ...            ...              ...
1465            1928           1091             1345
1466            1876           1081             1346
1467            1056           1052             1347
1468            1012           1051             1348
1469             701           1009             1349

[1470 rows x 3 columns]

## Query 30 – Employee Numbering by Department

### Objective

Assign row numbers within each department.

In [63]:
query = """
SELECT
    EmployeeNumber,
    Department,
    ROW_NUMBER() OVER(
        PARTITION BY Department
        ORDER BY MonthlyIncome DESC
    ) AS RowNum
FROM employees;
"""

pd.read_sql(query, conn)

      EmployeeNumber       Department  RowNum
0               1338  Human Resources       1
1               1625  Human Resources       2
2               1973  Human Resources       3
3                734  Human Resources       4
4                731  Human Resources       5
...              ...              ...     ...
1465             411            Sales     442
1466            1273            Sales     443
1467            1928            Sales     444
1468            1876            Sales     445
1469            1056            Sales     446

[1470 rows x 3 columns]

In [64]:
conn.close()

print("Database connection closed.")

Database connection closed.

# Day 6 Summary

## Skills Learned

- SQL Aggregations
- GROUP BY
- HAVING
- Subqueries
- ORDER BY
- LIMIT
- CASE WHEN
- Window Functions
  - RANK()
  - DENSE_RANK()
  - ROW_NUMBER()
  - AVG() OVER()

## Business Insights

- Department-wise attrition
- Salary analysis
- Employee rankings
- Department salary comparison
- High-income employee identification

## Next Step

Build interactive HR dashboards in Power BI using the cleaned dataset and SQL-derived business insights.